### ISSUE TITLE
Stacktrace in webapp: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by eegoodman** [TIBCOSoftware/fabrician-dynamic-variable-provider#1] opened 2013-07-10 15:09 UTC
I followed the readme and built the project, edited the deployment descriptor as in the readme, deployed the dynamic variable provider jar file and deployment descriptor, renamed the war file to vpw.war and it seemed to all work.  However, on the web container console I got the following stack trace.  (I'm using jboss 7 to deploy webapp).

17:08:16,130 INFO  [org.jboss.as.server](DeploymentScanner-threads - 2) JBAS018559: Deployed "vpw.war"
17:08:21,662 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/vpw].[management]](http--127.0.0.1-9090-5) Servlet.service() for servlet management threw exception:
java.util.NoSuchElementException
        at java.util.LinkedList.removeFirst(LinkedList.java:268) [rt.jar:1.7.0_07]
        at org.fabrican.extension.variable.provider.dao.ConnectionManager.getConnection(ConnectionManager.java:34) [classes:]
        at org.fabrican.extension.variable.provider.dao.RuleSetDAO.listRules(RuleSetDAO.java:70) [classes:]
        at org.fabrican.extension.variable.provider.servlet.ManagementServlet.getListJSON(ManagementServlet.java:257) [classes:]
        at org.fabrican.extension.variable.provider.servlet.ManagementServlet.doGet(ManagementServlet.java:63) [classes:]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
        at java.lang.Thread.run(Thread.java:722) [rt.jar:1.7.0_07]

**Comment by ffan632** [comment] 2013-07-10 17:29
This stack trace can be reproduced when the JDBC connection is not configured. The problem is now fixed.

**Closed as completed** 2013-07-10 17:30 UTC
